// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_for_access_token_auth_token_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_for_access_token_auth_token_post'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        available: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Available',
            default: true
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        website_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website Url'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ItemCreate'
} as const;

export const ItemListResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ItemRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['items', 'total'],
    title: 'ItemListResponse',
    example: {
        items: [
            {
                created_at: '2024-01-01T12:00:00Z',
                description: 'This is an example item.',
                id: 1,
                image_url: 'https://example.com/logo.png',
                name: 'Example Item',
                owner_id: 1,
                rating: 5,
                slug: 'example-item',
                updated_at: '2024-01-02T12:00:00Z',
                website_url: 'https://example.com'
            }
        ],
        total: 1
    }
} as const;

export const ItemReadSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        available: {
            type: 'boolean',
            title: 'Available',
            default: true
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        website_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website Url'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        owner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserRead'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ItemRead'
} as const;

export const ItemUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        available: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Available'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        website_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website Url'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token',
            description: 'Refresh token to obtain a new access token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshTokenRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token',
            description: 'JWT access token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token',
            description: 'JWT refresh token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            description: "Type of the token, typically 'bearer'",
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token'],
    title: 'Token'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Username',
            description: 'Unique username following Google Workspace guidelines'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email',
            description: "User's email address (optional)"
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url',
            description: "URL to the user's avatar image"
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            description: 'Indicates if the user account is active',
            default: true
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser',
            description: 'Indicates if the user has superuser privileges',
            default: false
        },
        password: {
            type: 'string',
            minLength: 8,
            title: 'Password',
            description: 'Password for the user account, at least 8 characters'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserCreate'
} as const;

export const UserListResponseSchema = {
    properties: {
        users: {
            items: {
                '$ref': '#/components/schemas/UserRead'
            },
            type: 'array',
            title: 'Users',
            description: 'List of users'
        },
        total: {
            type: 'integer',
            title: 'Total',
            description: 'Total number of users'
        },
        skip: {
            type: 'integer',
            title: 'Skip',
            description: 'Number of users skipped'
        },
        limit: {
            type: 'integer',
            title: 'Limit',
            description: 'Maximum number of users returned'
        }
    },
    type: 'object',
    required: ['users', 'total', 'skip', 'limit'],
    title: 'UserListResponse'
} as const;

export const UserPasswordUpdateSchema = {
    properties: {
        current_password: {
            type: 'string',
            title: 'Current Password',
            description: 'Current password of the user'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password',
            description: 'New password for the user account, at least 8 characters'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UserPasswordUpdate'
} as const;

export const UserReadSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Username',
            description: 'Unique username following Google Workspace guidelines'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email',
            description: "User's email address (optional)"
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url',
            description: "URL to the user's avatar image"
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            description: 'Indicates if the user account is active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            description: 'Indicates if the user has superuser privileges'
        },
        id: {
            type: 'integer',
            title: 'Id',
            description: 'Unique identifier for the user'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'Timestamp when the user account was created'
        }
    },
    type: 'object',
    required: ['username', 'is_superuser', 'id', 'created_at'],
    title: 'UserRead'
} as const;

export const UserUpdateSchema = {
    properties: {
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url',
            description: "New URL to the user's avatar image"
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email',
            description: 'New email address for the user (optional)'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            description: 'Indicates if the user account is active (optional)'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser',
            description: 'Indicates if the user has superuser privileges (optional)'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;