// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { RegisterUserAuthRegisterPostData, RegisterUserAuthRegisterPostResponse, LoginForAccessTokenAuthTokenPostData, LoginForAccessTokenAuthTokenPostResponse, RefreshAccessTokenAuthRefreshPostData, RefreshAccessTokenAuthRefreshPostResponse, ReadUsersMeAuthMeGetResponse, UpdateUsersMeAuthMePatchData, UpdateUsersMeAuthMePatchResponse, UpdateUsersPasswordAuthPasswordPutData, UpdateUsersPasswordAuthPasswordPutResponse, HeadRootHealthHeadResponse, ListItemsApiV1ItemsGetData, ListItemsApiV1ItemsGetResponse, CreateItemApiV1ItemsPostData, CreateItemApiV1ItemsPostResponse, GetItemBySlugApiV1ItemsItemSlugGetData, GetItemBySlugApiV1ItemsItemSlugGetResponse, UpdateItemBySlugApiV1ItemsItemSlugPutData, UpdateItemBySlugApiV1ItemsItemSlugPutResponse, DeleteItemApiV1ItemsItemIdDeleteData, DeleteItemApiV1ItemsItemIdDeleteResponse, ReadRootGetResponse, ListUsersApiV1UsersGetData, ListUsersApiV1UsersGetResponse, CreateUserApiV1UsersPostData, CreateUserApiV1UsersPostResponse, GetUserByUsernameApiV1UsersUsernameGetData, GetUserByUsernameApiV1UsersUsernameGetResponse, UpdateUserByUsernameApiV1UsersUsernamePutData, UpdateUserByUsernameApiV1UsersUsernamePutResponse, DeleteUserByUsernameApiV1UsersUsernameDeleteData, DeleteUserByUsernameApiV1UsersUsernameDeleteResponse } from './types.gen';

export class AuthorizationProfileService {
    /**
     * Register User
     * Register a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserRead Successful Response
     * @throws ApiError
     */
    public static registerUserAuthRegisterPost(data: RegisterUserAuthRegisterPostData): CancelablePromise<RegisterUserAuthRegisterPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/auth/register',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Login For Access Token
     * Authenticate user and return access and refresh tokens.
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginForAccessTokenAuthTokenPost(data: LoginForAccessTokenAuthTokenPostData): CancelablePromise<LoginForAccessTokenAuthTokenPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/auth/token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Refresh Access Token
     * Get a new access token using a refresh token.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static refreshAccessTokenAuthRefreshPost(data: RefreshAccessTokenAuthRefreshPostData): CancelablePromise<RefreshAccessTokenAuthRefreshPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/auth/refresh',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Users Me
     * Get current logged-in user's profile.
     * @returns UserRead Successful Response
     * @throws ApiError
     */
    public static readUsersMeAuthMeGet(): CancelablePromise<ReadUsersMeAuthMeGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/auth/me'
        });
    }
    
    /**
     * Update Users Me
     * Update current logged-in user's profile.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserRead Successful Response
     * @throws ApiError
     */
    public static updateUsersMeAuthMePatch(data: UpdateUsersMeAuthMePatchData): CancelablePromise<UpdateUsersMeAuthMePatchResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/auth/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Users Password
     * Update current logged-in user's password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updateUsersPasswordAuthPasswordPut(data: UpdateUsersPasswordAuthPasswordPutData): CancelablePromise<UpdateUsersPasswordAuthPasswordPutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/auth/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class HealthCheckService {
    /**
     * Head Root
     * Root endpoint providing health check via HEAD request.
     * This endpoint can be used to check if the API is up and running.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static headRootHealthHead(): CancelablePromise<HeadRootHealthHeadResponse> {
        return __request(OpenAPI, {
            method: 'HEAD',
            url: '/health'
        });
    }
    
}

export class ItemsService {
    /**
     * List Items
     * List items with filtering, sorting, and pagination.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.name
     * @param data.description
     * @param data.ownerId
     * @param data.sortField
     * @param data.sortDirection
     * @returns ItemListResponse Successful Response
     * @throws ApiError
     */
    public static listItemsApiV1ItemsGet(data: ListItemsApiV1ItemsGetData = {}): CancelablePromise<ListItemsApiV1ItemsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit,
                name: data.name,
                description: data.description,
                owner_id: data.ownerId,
                sort_field: data.sortField,
                sort_direction: data.sortDirection
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create a new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemRead Successful Response
     * @throws ApiError
     */
    public static createItemApiV1ItemsPost(data: CreateItemApiV1ItemsPostData): CancelablePromise<CreateItemApiV1ItemsPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Item By Slug
     * Get a specific item by its slug.
     * @param data The data for the request.
     * @param data.itemSlug
     * @returns ItemRead Successful Response
     * @throws ApiError
     */
    public static getItemBySlugApiV1ItemsItemSlugGet(data: GetItemBySlugApiV1ItemsItemSlugGetData): CancelablePromise<GetItemBySlugApiV1ItemsItemSlugGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{item_slug}',
            path: {
                item_slug: data.itemSlug
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item By Slug
     * Update an item by slug.
     * @param data The data for the request.
     * @param data.itemSlug
     * @param data.requestBody
     * @returns ItemRead Successful Response
     * @throws ApiError
     */
    public static updateItemBySlugApiV1ItemsItemSlugPut(data: UpdateItemBySlugApiV1ItemsItemSlugPutData): CancelablePromise<UpdateItemBySlugApiV1ItemsItemSlugPutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{item_slug}',
            path: {
                item_slug: data.itemSlug
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.itemId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteItemApiV1ItemsItemIdDelete(data: DeleteItemApiV1ItemsItemIdDeleteData): CancelablePromise<DeleteItemApiV1ItemsItemIdDeleteResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{item_id}',
            path: {
                item_id: data.itemId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class RootService {
    /**
     * Read Root
     * Root endpoint providing basic API information.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readRootGet(): CancelablePromise<ReadRootGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
    
}

export class UsersService {
    /**
     * List Users
     * List users with filtering, sorting, and pagination.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.username
     * @param data.email
     * @param data.isActive
     * @param data.sortField
     * @param data.sortDirection
     * @returns UserListResponse Successful Response
     * @throws ApiError
     */
    public static listUsersApiV1UsersGet(data: ListUsersApiV1UsersGetData = {}): CancelablePromise<ListUsersApiV1UsersGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit,
                username: data.username,
                email: data.email,
                is_active: data.isActive,
                sort_field: data.sortField,
                sort_direction: data.sortDirection
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserRead Successful Response
     * @throws ApiError
     */
    public static createUserApiV1UsersPost(data: CreateUserApiV1UsersPostData): CancelablePromise<CreateUserApiV1UsersPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User By Username
     * Get a specific user by username.
     * @param data The data for the request.
     * @param data.username
     * @returns UserRead Successful Response
     * @throws ApiError
     */
    public static getUserByUsernameApiV1UsersUsernameGet(data: GetUserByUsernameApiV1UsersUsernameGetData): CancelablePromise<GetUserByUsernameApiV1UsersUsernameGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{username}',
            path: {
                username: data.username
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User By Username
     * Update a user by username.
     * @param data The data for the request.
     * @param data.username
     * @param data.requestBody
     * @returns UserRead Successful Response
     * @throws ApiError
     */
    public static updateUserByUsernameApiV1UsersUsernamePut(data: UpdateUserByUsernameApiV1UsersUsernamePutData): CancelablePromise<UpdateUserByUsernameApiV1UsersUsernamePutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/users/{username}',
            path: {
                username: data.username
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User By Username
     * Delete a user by username.
     * @param data The data for the request.
     * @param data.username
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteUserByUsernameApiV1UsersUsernameDelete(data: DeleteUserByUsernameApiV1UsersUsernameDeleteData): CancelablePromise<DeleteUserByUsernameApiV1UsersUsernameDeleteResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{username}',
            path: {
                username: data.username
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}