// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_for_access_token_auth_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    name: string;
    slug?: (string | null);
    description?: (string | null);
    rating?: (number | null);
    available?: (boolean | null);
    image_url?: (string | null);
    website_url?: (string | null);
};

export type ItemListResponse = {
    items: Array<ItemRead>;
    total: number;
};

export type ItemRead = {
    name: string;
    slug: string;
    description?: (string | null);
    rating?: (number | null);
    available?: boolean;
    image_url?: (string | null);
    website_url?: (string | null);
    id: number;
    created_at?: (string | null);
    updated_at?: (string | null);
    owner?: (UserRead | null);
};

export type ItemUpdate = {
    name?: (string | null);
    slug?: (string | null);
    description?: (string | null);
    rating?: (number | null);
    available?: (boolean | null);
    image_url?: (string | null);
    website_url?: (string | null);
};

export type Message = {
    message: string;
};

export type RefreshTokenRequest = {
    /**
     * Refresh token to obtain a new access token
     */
    refresh_token: string;
};

export type Token = {
    /**
     * JWT access token
     */
    access_token: string;
    /**
     * JWT refresh token
     */
    refresh_token: string;
    /**
     * Type of the token, typically 'bearer'
     */
    token_type?: string;
};

export type UserCreate = {
    /**
     * Unique username following Google Workspace guidelines
     */
    username: string;
    /**
     * User's email address (optional)
     */
    email?: (string | null);
    /**
     * URL to the user's avatar image
     */
    avatar_url?: (string | null);
    /**
     * Indicates if the user account is active
     */
    is_active?: boolean;
    /**
     * Indicates if the user has superuser privileges
     */
    is_superuser?: boolean;
    /**
     * Password for the user account, at least 8 characters
     */
    password: string;
};

export type UserListResponse = {
    /**
     * List of users
     */
    users: Array<UserRead>;
    /**
     * Total number of users
     */
    total: number;
    /**
     * Number of users skipped
     */
    skip: number;
    /**
     * Maximum number of users returned
     */
    limit: number;
};

export type UserPasswordUpdate = {
    /**
     * Current password of the user
     */
    current_password: string;
    /**
     * New password for the user account, at least 8 characters
     */
    new_password: string;
};

export type UserRead = {
    /**
     * Unique username following Google Workspace guidelines
     */
    username: string;
    /**
     * User's email address (optional)
     */
    email?: (string | null);
    /**
     * URL to the user's avatar image
     */
    avatar_url?: (string | null);
    /**
     * Indicates if the user account is active
     */
    is_active?: boolean;
    /**
     * Indicates if the user has superuser privileges
     */
    is_superuser: boolean;
    /**
     * Unique identifier for the user
     */
    id: number;
    /**
     * Timestamp when the user account was created
     */
    created_at: string;
};

export type UserUpdate = {
    /**
     * New URL to the user's avatar image
     */
    avatar_url?: (string | null);
    /**
     * New email address for the user (optional)
     */
    email?: (string | null);
    /**
     * Indicates if the user account is active (optional)
     */
    is_active?: (boolean | null);
    /**
     * Indicates if the user has superuser privileges (optional)
     */
    is_superuser?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RegisterUserAuthRegisterPostData = {
    requestBody: UserCreate;
};

export type RegisterUserAuthRegisterPostResponse = (UserRead);

export type LoginForAccessTokenAuthTokenPostData = {
    formData: Body_login_for_access_token_auth_token_post;
};

export type LoginForAccessTokenAuthTokenPostResponse = (Token);

export type RefreshAccessTokenAuthRefreshPostData = {
    requestBody: RefreshTokenRequest;
};

export type RefreshAccessTokenAuthRefreshPostResponse = (Token);

export type ReadUsersMeAuthMeGetResponse = (UserRead);

export type UpdateUsersMeAuthMePatchData = {
    requestBody: UserUpdate;
};

export type UpdateUsersMeAuthMePatchResponse = (UserRead);

export type UpdateUsersPasswordAuthPasswordPutData = {
    requestBody: UserPasswordUpdate;
};

export type UpdateUsersPasswordAuthPasswordPutResponse = (Message);

export type HeadRootHealthHeadResponse = (unknown);

export type ListItemsApiV1ItemsGetData = {
    description?: string;
    limit?: number;
    name?: string;
    ownerId?: number;
    skip?: number;
    sortDirection?: string;
    sortField?: string;
};

export type ListItemsApiV1ItemsGetResponse = (ItemListResponse);

export type CreateItemApiV1ItemsPostData = {
    requestBody: ItemCreate;
};

export type CreateItemApiV1ItemsPostResponse = (ItemRead);

export type GetItemBySlugApiV1ItemsItemSlugGetData = {
    itemSlug: string;
};

export type GetItemBySlugApiV1ItemsItemSlugGetResponse = (ItemRead);

export type UpdateItemBySlugApiV1ItemsItemSlugPutData = {
    itemSlug: string;
    requestBody: ItemUpdate;
};

export type UpdateItemBySlugApiV1ItemsItemSlugPutResponse = (ItemRead);

export type DeleteItemApiV1ItemsItemIdDeleteData = {
    itemId: number;
};

export type DeleteItemApiV1ItemsItemIdDeleteResponse = (void);

export type ReadRootGetResponse = (unknown);

export type ListUsersApiV1UsersGetData = {
    email?: string;
    isActive?: boolean;
    limit?: number;
    skip?: number;
    sortDirection?: string;
    sortField?: string;
    username?: string;
};

export type ListUsersApiV1UsersGetResponse = (UserListResponse);

export type CreateUserApiV1UsersPostData = {
    requestBody: UserCreate;
};

export type CreateUserApiV1UsersPostResponse = (UserRead);

export type GetUserByUsernameApiV1UsersUsernameGetData = {
    username: string;
};

export type GetUserByUsernameApiV1UsersUsernameGetResponse = (UserRead);

export type UpdateUserByUsernameApiV1UsersUsernamePutData = {
    requestBody: UserUpdate;
    username: string;
};

export type UpdateUserByUsernameApiV1UsersUsernamePutResponse = (UserRead);

export type DeleteUserByUsernameApiV1UsersUsernameDeleteData = {
    username: string;
};

export type DeleteUserByUsernameApiV1UsersUsernameDeleteResponse = (void);